name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install
      run: npm ci

    - name: Build
      run: npm run build

    - name: Test
      run: npm run test
